server:
  port: 8899
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/qqproject?characterEncoding=UTF-8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
